import {
    ElButton,
    ElIcon,
    ElRow,
    ElSelect,
    ElInput,
    ElLink,
    ElDropdown,
    ElAvatar,
    ElRadioGroup,
    ElRadio,
    ElRadioButton,
    ElMenu,
    ElSubMenu,
    ElMenuItem,
    ElMenuItemGroup,
    ElDropdownMenu,
    ElDropdownItem,
    ElTag,
    ElCarousel,
    ElCarouselItem,
    ElTable,
    ElTableColumn,
    ElCollapse,
    ElCollapseItem,
    ElForm,
    ElFormItem,
    ElSteps,
    ElStep,
    ElPagination,
    ElDialog,
    ElCheckboxGroup,
    ElCheckbox,
    ElTabs,
    ElTabPane,

    ElButtonGroup,
    ElDivider,
    ElCol,
    ElOption,
    ElDatePicker,
    ElTimePicker,
    ElSwitch,
    ElBacktop,
    ElHeader,
    ElMain,
    ElAffix,
    ElCard,
    ElDescriptions,
    ElDescriptionsItem,
    ElMessage,
    ElMessageBox,
    ElBreadcrumb,
    ElBreadcrumbItem,
    ElCascader,
} from "element-plus";

import {
    View,
    Share,
    Delete,
    Search,
    Calendar,
    Message,
    ArrowRightBold,
    Expand,
    Edit,
    Upload,
    SuccessFilled,
    Clock,
    User,
    DeleteFilled,
    Notebook,
    Medal,
    Star,
    Pointer,
    ChatDotRound,
    UserFilled,
    Location,
    Document,
    Setting,
} from "@element-plus/icons-vue";

const components = [
    ElButton,
    ElIcon,
    ElRow,
    ElSelect,
    ElInput,
    ElLink,
    ElDropdown,
    ElAvatar,
    ElDropdownItem,
    ElDropdownMenu,
    ElAvatar,
    ElRadioGroup,
    ElRadio,
    ElRadioButton,
    ElMenu,
    ElSubMenu,
    ElMenuItem,
    ElMenuItemGroup,
    ElTag,
    ElCarousel,
    ElCarouselItem,
    ElTable,
    ElTableColumn,
    ElCollapse,
    ElCollapseItem,
    ElForm,
    ElFormItem,
    ElSteps,
    ElStep,
    ElPagination,
    ElDialog,
    ElCheckboxGroup,
    ElCheckbox,
    ElTabs,
    ElTabPane,
    ElButtonGroup,
    ElDivider,
    ElCol,
    ElOption,
    ElDatePicker,
    ElTimePicker,
    ElSwitch,
    ElDescriptions,
    ElBacktop,
    ElHeader,
    ElMain,
    ElAffix,
    ElCard,
    ElDescriptionsItem,
    ElMessage,
    ElMessageBox,
    ElBreadcrumb,
    ElBreadcrumbItem,
    ElCascader,
]
const icons = [
    View,
    Share,
    Delete,
    Search,
    Calendar,
    Message,
    ArrowRightBold,
    Expand,
    Edit,
    Upload,
    SuccessFilled,
    Clock,
    User,
    DeleteFilled,
    Notebook,
    Medal,
    Star,
    Pointer,
    ChatDotRound,
    UserFilled,
    Location,
    Document,
    Setting,
]
const importElement = (app) => {
    components.forEach((component) => {
        app.component(component.name, component)
    })

    icons.forEach((icons) => {
        if(icons.name!=='View'){
            app.component(icons.name, icons)
        }else{
            app.component('MyView',icons)
        }

    })
}

export {
    importElement
}
